package interpreter

// EventType represents the type of execution event.
type EventType int

const (
	// EventRapidMove is a rapid positioning move (G0).
	EventRapidMove EventType = iota
	// EventLinearCut is a linear interpolation cut (G1).
	EventLinearCut
	// EventArcCW is a clockwise arc cut (G2).
	EventArcCW
	// EventArcCCW is a counter-clockwise arc cut (G3).
	EventArcCCW
	// EventDrillCycle is a drilling cycle.
	EventDrillCycle
	// EventToolChange is a tool change operation.
	EventToolChange
	// EventSpindleStart is a spindle start command.
	EventSpindleStart
	// EventSpindleStop is a spindle stop command.
	EventSpindleStop
	// EventUnitChange is a unit change (G20/G21).
	EventUnitChange
	// EventModeChange is a positioning mode change (G90/G91).
	EventModeChange
)

// String returns the string representation of the event type.
func (e EventType) String() string {
	switch e {
	case EventRapidMove:
		return "RapidMove"
	case EventLinearCut:
		return "LinearCut"
	case EventArcCW:
		return "ArcCW"
	case EventArcCCW:
		return "ArcCCW"
	case EventDrillCycle:
		return "DrillCycle"
	case EventToolChange:
		return "ToolChange"
	case EventSpindleStart:
		return "SpindleStart"
	case EventSpindleStop:
		return "SpindleStop"
	case EventUnitChange:
		return "UnitChange"
	case EventModeChange:
		return "ModeChange"
	default:
		return "Unknown"
	}
}

// Event represents a single execution event generated by the interpreter.
type Event struct {
	// Type is the type of event.
	Type EventType

	// From is the starting position (for motion events).
	From Position

	// To is the ending position (for motion events).
	To Position

	// Feed is the feed rate used (for cutting moves).
	Feed float64

	// Tool is the tool number involved (for tool changes).
	Tool int

	// Spindle is the spindle speed (for spindle events).
	Spindle float64

	// SpindleCW indicates clockwise rotation for spindle events.
	SpindleCW bool

	// Unit is the new unit (for unit change events).
	Unit Unit

	// Mode is the new mode (for mode change events).
	Mode PositionMode

	// Arc contains arc-specific data (for G2/G3).
	Arc *ArcData

	// SourceLine is the original source line number.
	SourceLine int
}

// ArcData contains data specific to arc movements.
type ArcData struct {
	// Center is the arc center point.
	Center Position

	// Radius is the arc radius.
	Radius float64

	// I, J, K are the center offsets from the start point.
	I, J, K float64

	// Clockwise indicates if the arc is clockwise (true) or CCW (false).
	Clockwise bool
}

// ExecutionTrace represents the complete trace of executing a G-code program.
type ExecutionTrace struct {
	// Events is the ordered list of execution events.
	Events []Event

	// FinalState is the machine state after execution.
	FinalState *MachineState
}

// NewExecutionTrace creates a new empty execution trace.
func NewExecutionTrace() *ExecutionTrace {
	return &ExecutionTrace{
		Events:     make([]Event, 0),
		FinalState: NewMachineState(),
	}
}

// AddEvent adds an event to the trace.
func (t *ExecutionTrace) AddEvent(e Event) {
	t.Events = append(t.Events, e)
}

// EventCount returns the total number of events.
func (t *ExecutionTrace) EventCount() int {
	return len(t.Events)
}

// EventsOfType returns all events of a specific type.
func (t *ExecutionTrace) EventsOfType(eventType EventType) []Event {
	var result []Event
	for _, e := range t.Events {
		if e.Type == eventType {
			result = append(result, e)
		}
	}
	return result
}

// RapidMoves returns all rapid move events.
func (t *ExecutionTrace) RapidMoves() []Event {
	return t.EventsOfType(EventRapidMove)
}

// LinearCuts returns all linear cut events.
func (t *ExecutionTrace) LinearCuts() []Event {
	return t.EventsOfType(EventLinearCut)
}

// ArcCuts returns all arc cut events (both CW and CCW).
func (t *ExecutionTrace) ArcCuts() []Event {
	var result []Event
	for _, e := range t.Events {
		if e.Type == EventArcCW || e.Type == EventArcCCW {
			result = append(result, e)
		}
	}
	return result
}

// ToolChanges returns all tool change events.
func (t *ExecutionTrace) ToolChanges() []Event {
	return t.EventsOfType(EventToolChange)
}
